# Generated by Django 4.1.3 on 2022-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
