# Generated by Django 4.1.3 on 2022-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_coments_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coments',
            new_name='Coment',
        ),
    ]
