# Generated by Django 4.1.3 on 2022-12-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_country_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_number',
        ),
    ]
