# Generated by Django 4.1.3 on 2023-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
