# Generated by Django 4.1.3 on 2022-12-10 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=40)),
                ('tel', models.CharField(blank=True, max_length=12, null=True)),
                ('cel', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('compania', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('notas', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
