# Generated by Django 4.1.3 on 2022-12-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_description', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=120)),
                ('quantity', models.IntegerField(default=10)),
            ],
        ),
    ]
