# Generated by Django 5.1.2 on 2024-10-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gestion_grafitis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafiti',
            name='imagen',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
